language: python
python:
  - "2.7"
before_install:
  - pip install pycodestyle  
install:
  - pip install -r requirements.txt
script:
  - find . -name \*.py -exec pycodestyle --ignore=E501 {} +  
notifications:
  email: false
